name: Deploy Web Wallet

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Check if the workflow was triggered by a tag (production) or a branch (staging)
      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "🔥 Using production environment"
            echo "CNAME=wallet.pactus.org" >> $GITHUB_ENV
          else
            echo "🧪 Using staging environment"
            echo "CNAME=wallet-beta.pactus.org" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: |
          echo "Installing dependencies with Yarn..."
          yarn install --immutable

      - name: Build wallet package
        run: cd packages/wallet && yarn build
        
      - name: Build web app
        run: cd apps/web && yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: web
          publish_dir: ./apps/web/out
          cname: ${{ env.CNAME }} 